### ISSUE TITLE
如何使用第三方的UI框架

### ISSUE THREAD

**Issue by wenboLee** [davidlin88/mpvue-vuex-demo#2]
找到一篇博客，有说怎么用第三方框架[链接](https://blog.csdn.net/weixin_39015132/article/details/81068367)
但是如果按照里面的方法，需要用到一个库[mpvue-entry](https://github.com/F-loat/mpvue-entry)
而且要改build/webpack.base.conf.js的配置
改了配置之后，小程序开发工具会报错，找不到app.json
刚入坑，想请教一下大佬~

**Comment by davidlin88** [comment]
1.跳过文章对配置的所有改动，使用案例中的第三方库的方法：在页面文件夹下的main.js，如`/me/main.js`内，增加类似如下代码，这里的配置可以打包后应用到页面级的json配置中：
```
export default {
}
```

**Comment by wenboLee** [comment]
嗯嗯，解决了，Thanks♪(･ω･)ﾉ
